### ISSUE TITLE
"Statute" is not the correct English term

### ISSUE THREAD

**Issue by cimm** [brug-be/articles_of_association#11]
The correct English term for "statue" / "statuten" / "statute" is "Articles of association". [Eurodicautom](iate.europa.eu/) is a useful resource to find these terms.

**Comment by toch** [comment]
but https://en.wikipedia.org/wiki/Statute

could you give a reference?

**Comment by cimm** [comment]
@toch: From your Wikipedia page: "that governs a **state, city or country**". I do like the idea of a Ruby Belgium state though...

I am no linguist but our legal department told us to use "Articles of association" for a similar document. Take it for what it's worth.

I will counter with another [Wikipedia link](https://en.wikipedia.org/wiki/Articles_of_association): "is a document which, along with the memorandum of association (in cases where the memorandum exists) form the **company's constitution**".

**Comment by toch** [comment]
fair enough

https://en.wikipedia.org/wiki/Articles_of_association

It seems to be the right term. Thanks @cimm :)

(sorry for the questions, your first comment mention `statue` which was mileading)

**Comment by cimm** [comment]
Should have taken more time explaining what I meant, blame the late hour, waiting for my tests to pass.

**Comment by toch** [comment]
fixed by fe91dda150b2b1fc4fae724a6595e34316ae1a95

no worries, eventually I understood, thanks for having spotted it!
